# Generated by Django 4.2.1 on 2023-05-04 11:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
                ('wallets', django.db.models.manager.Manager()),
            ],
        ),
    ]
