# Generated by Django 4.2.1 on 2023-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0002_alter_wallet_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
