# Generated by Django 4.2.1 on 2023-05-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletservice', '0004_rename_wallet_id_wallet_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
            ],
        ),
    ]
