# Generated by Django 4.2.1 on 2023-05-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walletservice', '0005_alter_wallet_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payee', to=settings.AUTH_USER_MODEL)),
                ('payee_wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payee_account', to='walletservice.wallet')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('payer_wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payer_account', to='walletservice.wallet')),
            ],
        ),
    ]
