# Generated by Django 4.2.1 on 2023-05-13 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walletservice', '0008_wallet_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payee_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payee_account_transactions', to='walletservice.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payer_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payer_account_transactions', to='walletservice.wallet'),
        ),
    ]
