# Generated by Django 4.2.1 on 2023-05-04 11:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
