# Generated by Django 4.2.1 on 2023-05-04 11:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0002_alter_userprofile_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('users', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
