# Generated by Django 4.2.1 on 2023-05-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0004_rename_user_name_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
