# Generated by Django 4.2.1 on 2023-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userservice', '0006_userprofile_is_staff_userprofile_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(null=True),
        ),
    ]
